#!/usr/bin/env python3
"""Generate natural-looking commits (0-21 per run, clustered or spread based on volume)."""
import os, random, datetime, subprocess

REPO = os.path.expanduser('~/rentsy-mcp')
os.chdir(REPO)

subprocess.run(['git', 'pull', '--rebase'], capture_output=True)

COMMITS = random.randint(0, 21)

if COMMITS == 0:
    print(f'Skipping {datetime.date.today()} — 0 commits today')
    exit(0)

# Spread pattern: many commits → spread wide, few → cluster tight
if COMMITS <= 3:
    # Cluster within 1 hour
    span_minutes = 60
elif COMMITS <= 7:
    # Within 3 hours
    span_minutes = 180
elif COMMITS <= 12:
    # Within 5 hours
    span_minutes = 300
else:
    # Spread across 8 hours
    span_minutes = 480

start_minute = random.randint(60, 240)  # start between 9am and 1pm
timestamps = sorted(random.sample(range(start_minute, start_minute + span_minutes), COMMITS))

commit_messages = [
    "chore: update activity heartbeat",
    "chore: automated data refresh",
    "chore: sync latest changes",
    "chore: periodic maintenance",
    "chore: update scraped timestamps",
    "chore: daily data sync",
    "chore: minor updates",
    "chore: bump heartbeat timestamp",
    "chore: refresh heartbeat log",
    "chore: sync heartbeat state",
    "chore: update heartbeat counter",
    "chore: bump activity tracker",
    "chore: refresh activity log",
    "chore: sync heartbeat data",
    "chore: update status tick",
    "chore: bump revision timestamp",
    "chore: refresh keepalive signal",
    "chore: sync liveness check",
    "chore: update pulse entry",
    "chore: routine heartbeat update",
    "chore: auto-sync heartbeat",
    "chore: periodic heartbeat tick",
    "chore: maintain activity log",
    "chore: update liveness record",
    "chore: sync availability flag",
    "chore: bump keepalive counter",
    "chore: refresh pulse data",
    "chore: update operational log",
    "chore: bump sync timestamp",
    "chore: auto-update heartbeat file",
    "chore: sync runtime state",
    "chore: periodic sync tick",
    "chore: update cycle counter",
    "chore: refresh state log",
    "chore: bump cycle timestamp",
    "chore: sync pulse entry",
    "chore: auto-refresh heartbeat",
    "chore: update runtime timestamp",
    "chore: bump liveness marker",
    "chore: refresh cycle log",
    "chore: sync operational state",
    "chore: periodic pulse update",
    "chore: update keepalive entry",
    "chore: bump activity marker",
    "chore: refresh sync timestamp",
    "chore: auto-sync state log",
    "chore: update pulse counter",
    "chore: routine sync update",
    "chore: bump operational timestamp",
    "chore: refresh liveness data",
    "chore: sync activity heartbeat",
    "chore: periodic state refresh",
    "chore: update sync tracker",
    "chore: bump runtime counter",
    "chore: refresh pulse timestamp",
    "chore: auto-update state log",
    "chore: sync heartbeat marker",
    "chore: maintenance cycle tick",
    "chore: update activity tracker",
    "chore: bump operational log",
    "chore: refresh keepalive timestamp",
    "chore: sync runtime heartbeat",
    "chore: periodic liveness check",
    "chore: update cycle timestamp",
    "chore: bump pulse marker",
    "chore: refresh sync state",
    "chore: auto-sync operational log",
    "chore: update runtime marker",
    "chore: routine heartbeat sync",
    "chore: bump state timestamp",
    "chore: refresh activity marker",
    "chore: sync keepalive counter",
    "chore: periodic heartbeat refresh",
    "chore: update liveness timestamp",
    "chore: bump pulse entry",
    "chore: refresh operational state",
    "chore: auto-update heartbeat",
    "chore: sync cycle counter",
    "chore: maintain pulse data",
    "chore: bump heartbeat state",
    "chore: refresh runtime log",
    "chore: sync activity update",
    "chore: periodic state sync",
    "chore: update operational pulse",
    "chore: bump sync heartbeat",
    "chore: refresh cycle timestamp",
    "chore: auto-sync pulse",
    "chore: update maintainer log",
    "chore: routine sync pulse",
    "chore: bump activity pulse",
    "chore: refresh state heartbeat",
    "chore: sync operational pulse",
    "chore: periodic update cycle",
    "chore: update heartbeat state",
    "chore: bump runtime pulse",
    "chore: refresh liveness pulse",
    "chore: auto-update state pulse",
    "chore: sync heartbeat cycle",
    "chore: maintenance pulse sync",
    "chore: bump state heartbeat",
    "chore: refresh operational pulse",
    "chore: sync runtime pulse",
    "chore: periodic maintainer tick",
    "chore: update pulse state",
    "chore: routine operation sync",
    "chore: bump operational pulse",
    "chore: refresh sync pulse",
    "chore: auto-sync runtime",
    "chore: update keepalive pulse",
    "chore: bump heartbeat marker",
    "chore: refresh pulse counter",
    "chore: sync maintainer log",
    "chore: periodic operation update",
    "chore: update state timestamp",
    "chore: routine pulse heartbeat",
    "chore: bump operational marker",
    "chore: refresh runtime counter",
    "chore: auto-update operational",
    "chore: sync pulse timestamp",
    "chore: maintenance runtime sync",
    "chore: update operational counter",
    "chore: bump state pulse",
    "chore: refresh keepalive pulse",
    "chore: sync cycle heartbeat",
    "chore: periodic auto-sync",
    "chore: update sync pulse",
    "chore: bump runtime heartbeat",
    "chore: refresh activity pulse",
    "chore: auto-sync operational",
    "chore: update operational state",
    "chore: routine maintenance tick",
    "chore: bump keepalive marker",
    "chore: refresh state counter",
    "chore: sync operational heartbeat",
    "chore: periodic cycle update",
    "chore: update runtime heartbeat",
    "chore: bump operational counter",
    "chore: refresh pulse heartbeat",
    "chore: auto-update runtime",
    "chore: sync heartbeat pulse",
    "chore: maintenance state sync",
    "chore: update pulse heartbeat",
    "chore: routine sync operation",
    "chore: bump heartbeat pulse",
    "chore: refresh runtime pulse",
    "chore: sync state pulse",
    "chore: periodic operational sync",
    "chore: update runtime state",
    "chore: bump operational sync",
    "chore: refresh heartbeat marker",
    "chore: auto-sync pulse state",
    "chore: update state heartbeat",
    "chore: maintenance pulse state",
    "chore: bump sync state",
    "chore: refresh operational sync",
    "chore: sync runtime marker",
    "chore: periodic state pulse",
    "chore: update operational heartbeat",
    "chore: routine runtime sync",
    "chore: bump pulse state",
    "chore: refresh heartbeat timestamp",
    "chore: auto-update operational state",
    "chore: sync marker heartbeat",
    "chore: maintenance sync pulse",
    "chore: update state marker",
    "chore: bump operational state",
    "chore: refresh runtime marker",
    "chore: sync pulse marker",
    "chore: periodic heartbeat state",
    "chore: update maintainer state",
    "chore: routine operational sync",
    "chore: bump runtime state",
    "chore: refresh operational marker",
    "chore: auto-sync heartbeat state",
    "chore: update pulse marker",
    "chore: maintenance operational state",
    "chore: bump marker heartbeat",
    "chore: refresh state marker",
    "chore: sync operational marker",
    "chore: periodic marker sync",
    "chore: update marker state",
    "chore: routine state sync",
    "chore: bump marker state",
    "chore: refresh marker sync",
    "chore: auto-update marker log",
    "chore: sync marker pulse",
    "chore: maintenance marker update",
    "chore: update log heartbeat",
    "chore: bump log state",
    "chore: refresh log pulse",
    "chore: sync log marker",
    "chore: periodic log update",
    "chore: update log timestamp",
    "chore: routine log sync",
    "chore: bump log heartbeat",
    "chore: refresh log timestamp",
    "chore: auto-sync log state",
    "chore: update state log",
    "chore: maintenance log update",
    "chore: bump timestamp log",
    "chore: refresh timestamp pulse",
    "chore: sync timestamp marker",
    "chore: periodic timestamp sync",
    "chore: update timestamp state",
    "chore: routine timestamp pulse",
    "chore: bump timestamp heartbeat",
    "chore: refresh timestamp log",
    "chore: auto-update timestamp",
    "chore: sync timestamp log",
    "chore: maintenance timestamp update",
    "chore: update counter log",
    "chore: bump counter state",
    "chore: refresh counter pulse",
    "chore: sync counter marker",
    "chore: periodic counter update",
    "chore: update counter timestamp",
    "chore: routine counter sync",
    "chore: bump counter heartbeat",
    "chore: refresh counter log",
    "chore: auto-sync counter state",
    "chore: update cycle state",
    "chore: maintenance counter update",
    "chore: bump cycle heartbeat",
    "chore: refresh cycle marker",
    "chore: sync cycle state",
    "chore: periodic cycle pulse",
    "chore: update cycle log",
    "chore: routine cycle heartbeat",
    "chore: bump state counter",
    "chore: refresh cycle counter",
    "chore: auto-update cycle timestamp",
    "chore: sync cycle log",
    "chore: maintenance cycle state",
    "chore: update pulse cycle",
    "chore: bump log counter",
    "chore: refresh log state",
    "chore: sync log counter",
    "chore: periodic log marker",
    "chore: update pulse counter",
    "chore: routine marker log",
    "chore: bump marker log",
    "chore: refresh marker count",
    "chore: auto-sync marker state",
    "chore: sync marker count",
    "chore: maintenance marker log",
    "chore: update marker count",
    "chore: bump marker timestamp",
    "chore: refresh state count",
    "chore: sync state marker",
    "chore: periodic state count",
    "chore: update state count",
    "chore: routine state marker",
    "chore: bump state count",
    "chore: refresh pulse count",
    "chore: auto-update state count",
    "chore: sync pulse count",
    "chore: maintenance state count",
    "chore: update count log",
    "chore: bump count state",
    "chore: refresh count pulse",
    "chore: sync count marker",
    "chore: periodic count update",
    "chore: update count timestamp",
    "chore: routine count sync",
    "chore: bump count heartbeat",
    "chore: refresh count log",
    "chore: auto-sync count state",
    "chore: update count state",
    "chore: maintenance count update",
    "chore: bump count marker",
    "chore: refresh count timestamp",
    "chore: sync count heartbeat",
    "chore: periodic count pulse",
    "chore: update count pulse",
    "chore: routine count marker",
    "chore: bump timestamp count",
    "chore: refresh heartbeat count",
    "chore: auto-update count pulse",
    "chore: sync count log",
    "chore: maintenance count state",
    "chore: update marker pulse",
    "chore: bump pulse count",
    "chore: refresh marker pulse",
    "chore: sync pulse log",
    "chore: periodic pulse marker",
    "chore: update pulse log",
    "chore: routine pulse state",
    "chore: bump log pulse",
    "chore: refresh log marker",
    "chore: auto-sync log pulse",
    "chore: sync state log",
    "chore: maintenance log pulse",
    "chore: update state pulse",
    "chore: bump log timestamp",
    "chore: refresh state pulse",
    "chore: sync marker timestamp",
    "chore: periodic marker pulse",
    "chore: update marker log",
    "chore: routine marker state",
    "chore: bump marker pulse",
    "chore: refresh marker state",
    "chore: auto-update marker timestamp",
    "chore: sync marker state",
    "chore: maintenance marker pulse",
    "chore: update timestamp marker",
    "chore: bump timestamp state",
    "chore: refresh timestamp counter",
    "chore: sync timestamp pulse",
    "chore: periodic timestamp marker",
    "chore: update timestamp counter",
    "chore: routine timestamp state",
    "chore: bump timestamp pulse",
    "chore: refresh timestamp heartbeat",
    "chore: auto-sync timestamp counter",
    "chore: sync counter log",
    "chore: maintenance timestamp state",
    "chore: update counter marker",
    "chore: bump counter log",
    "chore: refresh counter state",
    "chore: sync counter pulse",
    "chore: periodic counter marker",
    "chore: update counter heartbeat",
    "chore: routine counter state",
    "chore: bump counter pulse",
    "chore: refresh counter timestamp",
    "chore: auto-update counter log",
    "chore: sync counter timestamp",
    "chore: maintenance counter state",
    "chore: update heartbeat marker",
    "chore: bump heartbeat log",
    "chore: refresh heartbeat state",
    "chore: sync heartbeat pulse",
    "chore: periodic heartbeat marker",
    "chore: update heartbeat pulse",
    "chore: routine heartbeat state",
    "chore: bump heartbeat timestamp",
    "chore: refresh heartbeat counter",
    "chore: auto-sync heartbeat log",
    "chore: sync heartbeat timestamp",
    "chore: maintenance heartbeat state",
    "chore: update liveness marker",
    "chore: bump liveness timestamp",
    "chore: refresh liveness counter",
    "chore: sync liveness state",
    "chore: periodic liveness marker",
    "chore: update liveness counter",
    "chore: routine liveness state",
    "chore: bump liveness pulse",
    "chore: refresh liveness heartbeat",
    "chore: auto-update liveness log",
    "chore: sync liveness heartbeat",
    "chore: maintenance liveness state",
    "chore: update keepalive marker",
    "chore: bump keepalive timestamp",
    "chore: refresh keepalive counter",
    "chore: sync keepalive state",
    "chore: periodic keepalive marker",
    "chore: update keepalive counter",
    "chore: routine keepalive state",
    "chore: bump keepalive pulse",
    "chore: refresh keepalive heartbeat",
    "chore: auto-sync keepalive log",
    "chore: sync keepalive heartbeat",
    "chore: maintenance keepalive state",
    "chore: update pulse state",
    "chore: bump pulse log",
    "chore: refresh pulse marker",
    "chore: sync pulse heartbeat",
    "chore: periodic pulse counter",
    "chore: update pulse timestamp",
    "chore: routine pulse log",
    "chore: bump pulse heartbeat",
    "chore: refresh pulse cycle",
    "chore: auto-update pulse cycle",
    "chore: sync pulse cycle",
    "chore: maintenance pulse cycle",
    "chore: update log timestamp",
    "chore: bump log state",
    "chore: refresh log marker",
    "chore: sync log counter",
    "chore: periodic log pulse",
    "chore: update log state",
    "chore: routine log timestamp",
    "chore: bump log marker",
    "chore: refresh log counter",
    "chore: auto-sync log timestamp",
    "chore: sync log state",
    "chore: maintenance log counter",
    "chore: update marker state",
    "chore: bump marker counter",
    "chore: refresh marker pulse",
    "chore: sync marker log",
    "chore: periodic marker timestamp",
    "chore: update marker counter",
    "chore: routine marker log",
    "chore: bump marker timestamp",
    "chore: refresh marker heartbeat",
    "chore: auto-update marker pulse",
    "chore: sync marker counter",
    "chore: maintenance marker pulse",
    "chore: update state heartbeat",
    "chore: bump state marker",
    "chore: refresh state timestamp",
    "chore: sync state log",
    "chore: periodic state pulse",
    "chore: update state log",
    "chore: routine state timestamp",
    "chore: bump state heartbeat",
    "chore: refresh state counter",
    "chore: auto-sync state marker",
    "chore: sync state counter",
    "chore: maintenance state log",
    "chore: update counter state",
    "chore: bump counter marker",
    "chore: refresh counter heartbeat",
    "chore: sync counter log",
    "chore: periodic counter timestamp",
    "chore: update counter pulse",
    "chore: routine counter log",
    "chore: bump counter state",
    "chore: refresh counter marker",
    "chore: auto-update counter timestamp",
    "chore: sync counter state",
    "chore: maintenance counter log",
    "chore: update timestamp heart",
    "chore: bump timestamp marker",
    "chore: refresh timestamp state",
    "chore: sync timestamp log",
    "chore: periodic timestamp pulse",
    "chore: update timestamp state",
    "chore: routine timestamp marker",
    "chore: bump timestamp heartbeat",
    "chore: refresh timestamp counter",
    "chore: auto-sync timestamp pulse",
    "chore: sync timestamp state",
    "chore: maintenance timestamp marker",
    "chore: update heartbeat timestamp",
    "chore: bump heartbeat state",
    "chore: refresh heartbeat marker",
    "chore: sync heartbeat log",
    "chore: periodic heartbeat pulse",
    "chore: update heartbeat counter",
    "chore: routine heartbeat log",
    "chore: bump heartbeat marker",
    "chore: refresh heartbeat pulse",
    "chore: auto-update heartbeat timestamp",
    "chore: sync heartbeat state",
    "chore: maintenance heartbeat log",
    "chore: update runtime state",
    "chore: bump runtime marker",
    "chore: refresh runtime timestamp",
    "chore: sync runtime log",
    "chore: periodic runtime pulse",
    "chore: update runtime log",
    "chore: routine runtime marker",
    "chore: bump runtime heartbeat",
    "chore: refresh runtime counter",
    "chore: auto-sync runtime state",
    "chore: sync runtime counter",
    "chore: maintenance runtime log",
    "chore: update cycle marker",
    "chore: bump cycle timestamp",
    "chore: refresh cycle pulse",
    "chore: sync cycle log",
    "chore: periodic cycle state",
    "chore: update cycle pulse",
    "chore: routine cycle log",
    "chore: bump cycle heartbeat",
    "chore: refresh cycle counter",
    "chore: auto-update cycle state",
    "chore: sync cycle marker",
    "chore: maintenance cycle log",
    "chore: update state cycle",
    "chore: bump state timestamp",
    "chore: refresh state cycle",
    "chore: sync state cycle",
    "chore: periodic state cycle",
    "chore: update state cycle",
    "chore: routine state cycle",
    "chore: bump state cycle",
    "chore: refresh state cycle",
    "chore: auto-sync state cycle",
    "chore: sync state cycle",
    "chore: maintenance state cycle",
    "chore: update operation state",
    "chore: bump operation marker",
    "chore: refresh operation timestamp",
    "chore: sync operation log",
    "chore: periodic operation pulse",
    "chore: update operation log",
    "chore: routine operation marker",
    "chore: bump operation heartbeat",
    "chore: refresh operation counter",
    "chore: auto-update operation state",
    "chore: sync operation counter",
    "chore: maintenance operation log",
    "chore: update operation heartbeat",
    "chore: bump operation timestamp",
    "chore: refresh operation cycle",
    "chore: sync operation state",
    "chore: periodic operation cycle",
    "chore: update operation cycle",
    "chore: routine operation state",
    "chore: bump operation cycle",
    "chore: refresh operation marker",
    "chore: auto-sync operation cycle",
    "chore: sync operation sync",
    "chore: maintenance operation state",
]

for i, ts_minutes in enumerate(timestamps):
    hour = ts_minutes // 60
    minute = ts_minutes % 60
    second = random.randint(0, 59)
    today = datetime.date.today()
    ts = datetime.datetime(today.year, today.month, today.day, hour, minute, second)
    date_str = ts.strftime('%Y-%m-%d %H:%M:%S')

    with open(os.path.join(REPO, 'scripts', '.heartbeat'), 'a') as f:
        f.write(f'{ts.isoformat()} | commit-{i+1}/{COMMITS} | seed={random.getrandbits(16)}\n')

    subprocess.run(['git', 'add', 'scripts/.heartbeat'], capture_output=True)
    msg = random.choice(commit_messages)
    env = os.environ.copy()
    env['GIT_AUTHOR_DATE'] = date_str
    env['GIT_COMMITTER_DATE'] = date_str
    subprocess.run(['git', 'commit', '-m', msg], env=env, capture_output=True)
    subprocess.run(['sleep', str(random.randint(2, 10))])

subprocess.run(['git', 'push'], capture_output=True)
print(f'Pushed {COMMITS} commits for {datetime.date.today()}')
