"""
Seed demo data for Rentsy MCP — real products from www.rentsy.com.au
"""

import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from src.db.connection import get_client

PRODUCTS = [
    {"rentsy_slug": "floodlight--single-150w", "name": "Floodlight - Single (150w)", "description": "A floodlight illuminates larger areas like driveways, stages, warehouses, parking lots, or any other area that needs wide, even light coverage. 150w.", "url": "https://www.rentsy.com.au/gold-coast/stage-sound-lighting/floodlight--single-150w", "category_name": "Party + Events", "subcategory_name": "Stage, Sound + Lighting", "store_name": "Gold Coast Event Hire", "price": 12.00, "price_method": "per_day", "deposit": 50.00, "location_suburb": "Gold Coast", "location_city": "Gold Coast", "location_state": "QLD", "stock_available": 10, "is_available_today": True, "has_delivery": True, "has_pickup": True, "images": ["https://s3.us-east-2.amazonaws.com/website.rentsy/uploads/product_images/cropped/KUKJeiYnl8LUwOO7mYvs.jpg"], "features": ["150w floodlight", "Wide area coverage", "Stage lighting", "3 day hire period"]},
    {"rentsy_slug": "24m-Long-Trestle-Table", "name": "2.4M long trestle table", "description": "This 2.4M table seats 10 people and is non-folding trestle table. Go-to choice for weddings, corporate events and outdoor gatherings.", "url": "https://www.rentsy.com.au/gold-coast/Tables/24m-Long-Trestle-Table", "category_name": "Party + Events", "subcategory_name": "Tables", "store_name": "Gold Coast Party Hire", "price": 19.80, "price_method": "per_day", "deposit": 100.00, "location_suburb": "Hope Island", "location_city": "Gold Coast", "location_state": "QLD", "stock_available": 20, "is_available_today": True, "has_delivery": True, "has_pickup": True, "images": ["https://s3.us-east-2.amazonaws.com/website.rentsy/uploads/product_images/cropped/W71YrqRXEu4O6VXt4Uvf.jpg"], "features": ["Seats 10 people", "Non-folding", "2.4M length", "Suitable for weddings and events"]},
    {"rentsy_slug": "Double-Cocktail-Machine", "name": "Double Cocktail Machine", "description": "Double cocktail machine for parties and events. Serves delicious frozen cocktails. Perfect for weddings, parties and corporate events.", "url": "https://www.rentsy.com.au/gold-coast/Frozen-Drink-Machine/Double-Cocktail-Machine", "category_name": "Party + Events", "subcategory_name": "Cocktail Machine", "store_name": "Gold Coast Party Hire", "price": 190.00, "price_method": "per_day", "deposit": 200.00, "location_suburb": "Molendinar", "location_city": "Gold Coast", "location_state": "QLD", "stock_available": 3, "is_available_today": True, "has_delivery": True, "has_pickup": True, "images": ["https://s3.us-east-2.amazonaws.com/website.rentsy/uploads/product_images/cropped/XhEmpTdJ0TuL2xyyYVT3.jpg"], "features": ["Double machine", "Frozen cocktails", "Party hire", "Serves frozen drinks"]},
    {"rentsy_slug": "White-Candle-Stick-Holder-Set-Of-2", "name": "White Candle Stick Holder - Set of 2", "description": "Elegant white candle stick holders. Set of 2. Perfect for wedding ceremonies and event decor.", "url": "https://www.rentsy.com.au/gold-coast/candles-candleholders/White-Candle-Stick-Holder-Set-Of-2", "category_name": "Wedding", "subcategory_name": "Candles + Candleholders", "store_name": "Events by Design GC", "price": 12.00, "price_method": "per_day", "deposit": 20.00, "location_suburb": "Reedy Creek", "location_city": "Gold Coast", "location_state": "QLD", "stock_available": 15, "is_available_today": True, "has_delivery": True, "has_pickup": True, "images": ["https://s3.us-east-2.amazonaws.com/website.rentsy/uploads/product_images/cropped/lHKIIyYWkeH4dcpOJW05.jpg"], "features": ["Set of 2", "White color", "Elegant design", "Suitable for weddings"]},
    {"rentsy_slug": "60kva-Three-Phase-Cummins-Powered-Trailer-Mounted-Generator", "name": "60kVA - Three Phase - Trailer Mounted Generator", "description": "Powerful 60kVA three phase generator. Cummins powered, trailer mounted for easy transport. Ideal for events and construction sites.", "url": "https://www.rentsy.com.au/gold-coast/Generators/60kva-Three-Phase-Cummins-Powered-Trailer-Mounted-Generator", "category_name": "Tools + Machinery", "subcategory_name": "Generators", "store_name": "Gold Coast Generator Hire", "price": 300.00, "price_method": "per_day", "deposit": 500.00, "location_suburb": "Labrador", "location_city": "Gold Coast", "location_state": "QLD", "stock_available": 3, "is_available_today": True, "has_delivery": True, "has_pickup": True, "images": ["https://s3.us-east-2.amazonaws.com/website.rentsy/uploads/product_images/cropped/vKxBOGzm2lAzYomC1UcY.jpg"], "features": ["60kVA", "Three phase", "Cummins powered", "Trailer mounted"]},
    {"rentsy_slug": "House-Party-Pack", "name": "House Party Pack", "description": "Complete house party pack with everything you need for a great party at home. Sound system and lighting included.", "url": "https://www.rentsy.com.au/gold-coast/stage-sound-lighting/house-party-pack", "category_name": "Party + Events", "subcategory_name": "Stage, Sound + Lighting", "store_name": "Gold Coast Event Hire", "price": 154.00, "price_method": "per_day", "deposit": 200.00, "location_suburb": "Ashmore", "location_city": "Gold Coast", "location_state": "QLD", "stock_available": 5, "is_available_today": True, "has_delivery": True, "has_pickup": True, "images": ["https://s3.us-east-2.amazonaws.com/website.rentsy/uploads/product_images/cropped/7AdN0HKvyb9KdZhMPjpv.jpg"], "features": ["Complete party pack", "Sound system", "Lighting included"]},
    {"rentsy_slug": "naked-tipi-arbour", "name": "Naked Tipi Arbour", "description": "Beautiful naked tipi arbour perfect for weddings and events. Creates a stunning focal point for wedding ceremonies.", "url": "https://www.rentsy.com.au/gold-coast/arbours/naked-tipi-arbour", "category_name": "Wedding", "subcategory_name": "Arbours", "store_name": "Gold Coast Wedding Hire", "price": 300.00, "price_method": "per_day", "deposit": 250.00, "location_suburb": "Gold Coast", "location_city": "Gold Coast", "location_state": "QLD", "stock_available": 4, "is_available_today": False, "has_delivery": True, "has_pickup": False, "images": ["https://s3.us-east-2.amazonaws.com/website.rentsy/uploads/product_images/cropped/YnYgCNBz3VA8ZHiAWJez.jpg"], "features": ["Tipi design", "Naked timber", "Wedding ceremony focal point"]},
    {"rentsy_slug": "greenery-trellis-wall", "name": "Greenery Trellis Wall", "description": "Beautiful greenery trellis wall perfect for photo backdrops and event decoration.", "url": "https://www.rentsy.com.au/gold-coast/backdrops-photo-props/greenery-trellis-wall", "category_name": "Wedding", "subcategory_name": "Backdrops + Photo Props", "store_name": "Events by Design GC", "price": 150.00, "price_method": "per_day", "deposit": 100.00, "location_suburb": "Gold Coast", "location_city": "Gold Coast", "location_state": "QLD", "stock_available": 6, "is_available_today": True, "has_delivery": True, "has_pickup": True, "images": ["https://s3.us-east-2.amazonaws.com/website.rentsy/uploads/product_images/cropped/AFA9y4Xf3yvKjmsv5nrk.jpg"], "features": ["Greenery wall", "Photo backdrop", "Event decoration"]},
    {"rentsy_slug": "bond-tumblers-glasses", "name": "Bond Tumblers Glasses", "description": "Premium bond tumblers glasses for events and parties.", "url": "https://www.rentsy.com.au/gold-coast/glassware/Bond-Tumblers-Glasses", "category_name": "Party + Events", "subcategory_name": "Glassware", "store_name": "Gold Coast Party Hire", "price": 1.00, "price_method": "per_day", "deposit": 0, "location_suburb": "Helensvale", "location_city": "Gold Coast", "location_state": "QLD", "stock_available": 100, "is_available_today": True, "has_delivery": True, "has_pickup": True, "images": ["https://s3.us-east-2.amazonaws.com/website.rentsy/uploads/product_images/BQm6t8tqkCX6mxrmZLarMHIV4JohuPm2CLvrbs4W.jpg"], "features": ["Premium glassware", "Bond tumblers", "Party hire"]},
    {"rentsy_slug": "mexican-food-truck", "name": "Mexican Food Truck", "description": "Authentic Mexican food truck catering for your event. Serves delicious tacos, burritos and more.", "url": "https://www.rentsy.com.au/gold-coast/food-trucks-food-carts/Mexican-Food-Truck", "category_name": "Party + Events", "subcategory_name": "Catering", "store_name": "Gold Coast Food Trucks", "price": 28.00, "price_method": "per_person", "deposit": 200.00, "location_suburb": "Southport", "location_city": "Gold Coast", "location_state": "QLD", "stock_available": 2, "is_available_today": True, "has_delivery": True, "has_pickup": False, "images": ["https://s3.us-east-2.amazonaws.com/website.rentsy/uploads/product_images/cropped/o8XgnHsqhoGjwXEd4rPe.jpg"], "features": ["Mexican cuisine", "Full catering service", "Tacos, burritos, nachos"]},
    {"rentsy_slug": "15m-inflatable-obstacle-course", "name": "15m Inflatable Obstacle Course", "description": "15x4 meters inflatable obstacle course. Suitable for outdoors on grass only and indoors on hard surfaces. Huge fun for kids parties and events.", "url": "https://www.rentsy.com.au/gold-coast/inflatables/15m-Inflatable-Obstacle-Course", "category_name": "Kids Parties", "subcategory_name": "Inflatables", "store_name": "GC Inflatables", "price": 595.00, "price_method": "per_hour", "deposit": 300.00, "location_suburb": "Gaven", "location_city": "Gold Coast", "location_state": "QLD", "stock_available": 1, "is_available_today": True, "has_delivery": True, "has_pickup": False, "images": ["https://s3.us-east-2.amazonaws.com/website.rentsy/uploads/product_images/cropped/4KBzcC4YyEMsJm42A2VU.jpg"], "features": ["15x4 meters", "Obstacle course", "Free delivery", "Indoor/outdoor"]},
    {"rentsy_slug": "3m-x-3m-yellow-bouncy-house", "name": "3m x 3m Yellow Bouncy House", "description": "Get ready to bounce, laugh, and play all day long! Our 3x3M Bouncing House is the ultimate inflatable for kids. Compact in size but HUGE on fun.", "url": "https://www.rentsy.com.au/gold-coast/inflatables/3m-x-3m-Yellow-Bouncy-House", "category_name": "Kids Parties", "subcategory_name": "Jumping Castles", "store_name": "GC Inflatables", "price": 395.00, "price_method": "per_hour", "deposit": 200.00, "location_suburb": "Gaven", "location_city": "Gold Coast", "location_state": "QLD", "stock_available": 1, "is_available_today": True, "has_delivery": True, "has_pickup": False, "images": ["https://s3.us-east-2.amazonaws.com/website.rentsy/uploads/product_images/cropped/fpf3sV55dWvjzjJco8mP.jpg"], "features": ["3m x 3m", "Yellow bouncy house", "Free delivery", "Ages 3+"]},
    {"rentsy_slug": "fun-zone-inflatable-obstacle-course", "name": "Fun Zone Inflatable Obstacle Course", "description": "Fun Zone Inflatable Obstacle Course. Packed with challenges and fun for all ages.", "url": "https://www.rentsy.com.au/gold-coast/inflatables/Fun-Zone-Inflatable-Obstacle-Course", "category_name": "Kids Parties", "subcategory_name": "Inflatables", "store_name": "GC Inflatables", "price": 595.00, "price_method": "per_hour", "deposit": 300.00, "location_suburb": "Gaven", "location_city": "Gold Coast", "location_state": "QLD", "stock_available": 2, "is_available_today": True, "has_delivery": True, "has_pickup": False, "images": ["https://s3.us-east-2.amazonaws.com/website.rentsy/uploads/product_images/cropped/XbEDl7TAgNenUnxuZvlk.jpg"], "features": ["Obstacle course", "Fun zone", "Free delivery", "Kids party favorite"]},
    {"rentsy_slug": "wave-rider-inflatable-waterslide", "name": "Wave Rider Inflatable Waterslide", "description": "Wave Rider Inflatable Waterslide. Perfect for summer parties and poolside events.", "url": "https://www.rentsy.com.au/gold-coast/inflatables/Wave-Rider-Inflatable-Waterslide", "category_name": "Kids Parties", "subcategory_name": "Inflatables", "store_name": "GC Inflatables", "price": 495.00, "price_method": "per_hour", "deposit": 300.00, "location_suburb": "Gaven", "location_city": "Gold Coast", "location_state": "QLD", "stock_available": 2, "is_available_today": True, "has_delivery": True, "has_pickup": False, "images": ["https://s3.us-east-2.amazonaws.com/website.rentsy/uploads/product_images/cropped/RTPGmbs4i1YN31HcIrHL.jpg"], "features": ["Waterslide", "Inflatable", "Free delivery", "Summer fun"]},
    {"rentsy_slug": "inflatable-bungee-launch-run", "name": "Inflatable Bungee Launch Run", "description": "Inflatable Bungee Launch Run. Experience the thrill of running and being launched into the air.", "url": "https://www.rentsy.com.au/gold-coast/inflatables/Inflatable-Bungee-Launch-Run", "category_name": "Kids Parties", "subcategory_name": "Inflatables", "store_name": "GC Inflatables", "price": 595.00, "price_method": "per_hour", "deposit": 300.00, "location_suburb": "Gaven", "location_city": "Gold Coast", "location_state": "QLD", "stock_available": 1, "is_available_today": True, "has_delivery": True, "has_pickup": False, "images": ["https://s3.us-east-2.amazonaws.com/website.rentsy/uploads/product_images/cropped/wymuJjAwviRcg4diWYjO.jpg"], "features": ["Bungee run", "Inflatable", "Free delivery", "Action fun"]},
    {"rentsy_slug": "gladiator-duel-inflatable-ring", "name": "Gladiator Duel Inflatable Ring", "description": "Gladiator Duel Inflatable Ring. Battle your friends in this exciting inflatable dueling ring.", "url": "https://www.rentsy.com.au/gold-coast/inflatables/Gladiator-Duel-Inflatable-Ring", "category_name": "Kids Parties", "subcategory_name": "Inflatables", "store_name": "GC Inflatables", "price": 495.00, "price_method": "per_hour", "deposit": 300.00, "location_suburb": "Gaven", "location_city": "Gold Coast", "location_state": "QLD", "stock_available": 2, "is_available_today": True, "has_delivery": True, "has_pickup": False, "images": ["https://s3.us-east-2.amazonaws.com/website.rentsy/uploads/product_images/cropped/mT3zYmMKi8KZMWl4v5AA.jpg"], "features": ["Gladiator duel", "Inflatable ring", "Free delivery", "Group activity"]},
    {"rentsy_slug": "10m-colour-rush-obstacle-course", "name": "10m Colour Rush Inflatable Obstacle Course", "description": "10m Colour Rush Inflatable Obstacle Course. Bright and colorful obstacle course for endless fun.", "url": "https://www.rentsy.com.au/gold-coast/inflatables/10m-Colour-Rush-Inflatable-Obstacle-Course", "category_name": "Kids Parties", "subcategory_name": "Inflatables", "store_name": "GC Inflatables", "price": 495.00, "price_method": "per_hour", "deposit": 300.00, "location_suburb": "Gaven", "location_city": "Gold Coast", "location_state": "QLD", "stock_available": 2, "is_available_today": True, "has_delivery": True, "has_pickup": False, "images": ["https://s3.us-east-2.amazonaws.com/website.rentsy/uploads/product_images/cropped/ykodJxaX0jTsUDviqYCN.jpg"], "features": ["10m obstacle course", "Colorful", "Free delivery", "Kids fun"]},
    {"rentsy_slug": "15m-chaos-inflatable-obstacle-course", "name": "15m Chaos Inflatable Obstacle Course", "description": "15m Chaos Inflatable Obstacle Course. The ultimate challenge for kids and adults alike.", "url": "https://www.rentsy.com.au/gold-coast/inflatables/15m-Chaos-Inflatable-Obstacle-Course", "category_name": "Kids Parties", "subcategory_name": "Inflatables", "store_name": "GC Inflatables", "price": 595.00, "price_method": "per_hour", "deposit": 300.00, "location_suburb": "Gaven", "location_city": "Gold Coast", "location_state": "QLD", "stock_available": 1, "is_available_today": True, "has_delivery": True, "has_pickup": False, "images": ["https://s3.us-east-2.amazonaws.com/website.rentsy/uploads/product_images/cropped/g0WKVjKvUk6zIt5s9aO1.jpg"], "features": ["15m obstacle course", "Chaos course", "Free delivery", "Extreme fun"]},
    {"rentsy_slug": "red-carpet-themed-360-photo-booth", "name": "Red Carpet Themed 360 Photo Booth", "description": "Red Carpet Themed 360 Photo Booth. Capture stunning 360-degree videos at your event.", "url": "https://www.rentsy.com.au/gold-coast/photobooths/Red-Carpet-Themed-360-Photo-Booth", "category_name": "Kids Parties", "subcategory_name": "Photobooths", "store_name": "GC Photo Booths", "price": 199.00, "price_method": "per_hour", "deposit": 150.00, "location_suburb": "Gold Coast", "location_city": "Gold Coast", "location_state": "QLD", "stock_available": 2, "is_available_today": True, "has_delivery": True, "has_pickup": True, "images": ["https://s3.us-east-2.amazonaws.com/website.rentsy/uploads/product_images/cropped/4KBzcC4YyEMsJm42A2VU.jpg"], "features": ["360 video", "Photo booth", "Red carpet", "Instant booking"]},
    {"rentsy_slug": "white-hairpin-bar-tables", "name": "White hairpin bar tables", "description": "Stylish white hairpin bar tables. Perfect for cocktail events and standing receptions.", "url": "https://www.rentsy.com.au/gold-coast/Tables/White-hairpin-bar-tables", "category_name": "Party + Events", "subcategory_name": "Tables", "store_name": "Gold Coast Party Hire", "price": 88.00, "price_method": "per_day", "deposit": 80.00, "location_suburb": "Hope Island", "location_city": "Gold Coast", "location_state": "QLD", "stock_available": 8, "is_available_today": True, "has_delivery": True, "has_pickup": True, "images": ["https://s3.us-east-2.amazonaws.com/website.rentsy/uploads/product_images/cropped/W71YrqRXEu4O6VXt4Uvf.jpg"], "features": ["White hairpin", "Bar table", "Cocktail style", "Modern design"]},
    {"rentsy_slug": "charcuterie-cart-full-board", "name": "Charcuterie Cart - Full Board Serve", "description": "Charcuterie Cart - Full Board Serve (min 25 guests). Beautiful grazing boards for your event.", "url": "https://www.rentsy.com.au/gold-coast/catering/Charcuterie-Cart-Full-Board-Serve-Min-25-Guests", "category_name": "Party + Events", "subcategory_name": "Catering", "store_name": "Gold Coast Food Trucks", "price": 24.00, "price_method": "per_person", "deposit": 100.00, "location_suburb": "Gold Coast", "location_city": "Gold Coast", "location_state": "QLD", "stock_available": 3, "is_available_today": True, "has_delivery": True, "has_pickup": False, "images": ["https://s3.us-east-2.amazonaws.com/website.rentsy/uploads/product_images/cropped/AmTwjXHNvnhJFV00y2EP.jpg"], "features": ["Charcuterie", "Full board", "Catering", "Min 25 guests"]},
    {"rentsy_slug": "ninja-warrior-30m-obstacle-course", "name": "Ninja Warrior 30 meter obstacle course", "description": "Ninja Warrior 30 meter obstacle course. The ultimate challenge for thrill-seekers.", "url": "https://www.rentsy.com.au/gold-coast/inflatables/Ninja-Warrior-30-meter-obstacle-course", "category_name": "Kids Parties", "subcategory_name": "Inflatables", "store_name": "GC Inflatables", "price": 1600.00, "price_method": "per_day", "deposit": 500.00, "location_suburb": "Gold Coast", "location_city": "Gold Coast", "location_state": "QLD", "stock_available": 1, "is_available_today": True, "has_delivery": True, "has_pickup": False, "images": ["https://s3.us-east-2.amazonaws.com/website.rentsy/uploads/product_images/cropped/4KBzcC4YyEMsJm42A2VU.jpg"], "features": ["30 meters", "Ninja warrior", "Free delivery", "Extreme obstacle course"]},
    {"rentsy_slug": "yellow-open-jumping-castle", "name": "Yellow Open Jumping Castle", "description": "Yellow Open Jumping Castle. Classic jumping castle fun for kids of all ages.", "url": "https://www.rentsy.com.au/gold-coast/jumping-castles/Yellow-Open-Jumping-Castle", "category_name": "Kids Parties", "subcategory_name": "Jumping Castles", "store_name": "GC Inflatables", "price": 239.00, "price_method": "per_hour", "deposit": 200.00, "location_suburb": "Gold Coast", "location_city": "Gold Coast", "location_state": "QLD", "stock_available": 2, "is_available_today": True, "has_delivery": True, "has_pickup": False, "images": ["https://s3.us-east-2.amazonaws.com/website.rentsy/uploads/product_images/cropped/fpf3sV55dWvjzjJco8mP.jpg"], "features": ["Jumping castle", "Yellow", "Free delivery", "Kids party classic"]},
    {"rentsy_slug": "white-americana-chairs", "name": "White Americana Chairs", "description": "Classic White Americana Chairs. Elegant seating for weddings and events.", "url": "https://www.rentsy.com.au/gold-coast/chairs/White-Americana-Chairs", "category_name": "Wedding", "subcategory_name": "Chairs", "store_name": "Gold Coast Wedding Hire", "price": 6.60, "price_method": "per_day", "deposit": 50.00, "location_suburb": "Hope Island", "location_city": "Gold Coast", "location_state": "QLD", "stock_available": 50, "is_available_today": True, "has_delivery": True, "has_pickup": True, "images": ["https://s3.us-east-2.amazonaws.com/website.rentsy/uploads/product_images/cropped/W71YrqRXEu4O6VXt4Uvf.jpg"], "features": ["White Americana", "Wedding chair", "Classic design", "Stackable"]},
]

CATEGORIES = [
    {"name": "Party + Events", "slug": "Party-Events-hire", "item_count": 2275, "image_url": "https://s3.us-east-2.amazonaws.com/website.rentsy/uploads/category/RxALCbRZf939Dj4cA6Yj.jpg", "icon": "🎪"},
    {"name": "Wedding", "slug": "Wedding-hire", "item_count": 1861, "image_url": "https://s3.us-east-2.amazonaws.com/website.rentsy/uploads/category/wSy8JOHlPIZ6eLLm0LPi.jpg", "icon": "💍"},
    {"name": "Kids Parties", "slug": "kids-parties-hire", "item_count": 1130, "image_url": "https://s3.us-east-2.amazonaws.com/website.rentsy/uploads/category/5XDwDF9vRox3r2FAzdTT.jpg", "icon": "🎈"},
    {"name": "Corporate Events", "slug": "corporate-events-hire", "item_count": 1064, "image_url": "https://s3.us-east-2.amazonaws.com/website.rentsy/uploads/category/9TzHEXvj6TGERGzg8LY3.jpg", "icon": "💼"},
    {"name": "Fashion", "slug": "Fashion-hire", "item_count": 364, "image_url": "https://s3.us-east-2.amazonaws.com/website.rentsy/uploads/category/7Erbf34663T3P1o5xU6b.jpg", "icon": "👗"},
    {"name": "Electronics", "slug": "Electronics-hire", "item_count": 280, "image_url": "https://s3.us-east-2.amazonaws.com/website.rentsy/uploads/category/4diT6EWi0jNhfFQgDHri.jpg", "icon": "📱"},
    {"name": "Tools + Machinery", "slug": "tools-machinery-hire", "item_count": 209, "image_url": "https://s3.us-east-2.amazonaws.com/website.rentsy/category/T4C3QOaxfsIbGwPjzXW9n2fNrWkn5maLgCZ5gKjN.jpg", "icon": "🔧"},
    {"name": "Sport + Leisure", "slug": "Sport-Leisure-hire", "item_count": 177, "image_url": "https://s3.us-east-2.amazonaws.com/website.rentsy/uploads/category/8yewCgr6TehRumBYZJBG.jpg", "icon": "⚽"},
    {"name": "Services", "slug": "services-hire", "item_count": 168, "image_url": "https://s3.us-east-2.amazonaws.com/website.rentsy/uploads/category/edjxO9fp81Kb3kv47iAz.jpg", "icon": "🛠️"},
    {"name": "Automotive", "slug": "Automotive-hire", "item_count": 119, "image_url": "https://s3.us-east-2.amazonaws.com/website.rentsy/category/Cvn9FBMcIr71z88WrnC9rXZ8t3Hi4YLLlEYtyuwp.jpg", "icon": "🚗"},
    {"name": "Watersports", "slug": "Watersports-hire", "item_count": 109, "image_url": "https://s3.us-east-2.amazonaws.com/website.rentsy/uploads/category/YvakcaohWKyjfj6mQlvp.jpg", "icon": "🏄"},
    {"name": "Entertainment", "slug": "entertainment-hire", "item_count": 52, "image_url": "https://s3.us-east-2.amazonaws.com/website.rentsy/uploads/category/bSTJSlUyz45e6mL8C889.jpg", "icon": "🎵"},
    {"name": "Health + Fitness", "slug": "health-fitness-hire", "item_count": 45, "image_url": "https://s3.us-east-2.amazonaws.com/website.rentsy/uploads/category/AxhOgvB8lktRHcME82g6.jpg", "icon": "💪"},
    {"name": "Office", "slug": "Office-hire", "item_count": 24, "image_url": "https://s3.us-east-2.amazonaws.com/website.rentsy/uploads/category/EyXNiqcozMJHBMqJIWSt.jpg", "icon": "📋"},
    {"name": "Experiences", "slug": "experiences-hire", "item_count": 12, "image_url": "https://s3.us-east-2.amazonaws.com/website.rentsy/uploads/category/kAtZICTMW6cdDRfwTJhm.jpg", "icon": "🌟"},
    {"name": "Baby + Home", "slug": "baby-home-hire", "item_count": 111, "image_url": "https://s3.us-east-2.amazonaws.com/website.rentsy/uploads/category/rLn8uqdFQv02yWEE8huU.jpg", "icon": "🏠"},
    {"name": "Adventure", "slug": "Adventure-hire", "item_count": 100, "image_url": "https://s3.us-east-2.amazonaws.com/website.rentsy/uploads/category/b7QT69ngTCIGZFYgfrk7.jpg", "icon": "🏔️"},
    {"name": "Venues + Studios", "slug": "venues-studios-hire", "item_count": 67, "image_url": "https://s3.us-east-2.amazonaws.com/website.rentsy/uploads/category/HZvvSJMgY4CHl4h1Jrii.jpg", "icon": "🏢"},
]

STORES = [
    {"business_name": "Gold Coast Event Hire", "city": "Gold Coast", "state": "QLD", "rating": 4.8, "review_count": 127, "is_verified": True, "reply_time": "<5 min"},
    {"business_name": "Gold Coast Party Hire", "city": "Gold Coast", "state": "QLD", "rating": 4.7, "review_count": 89, "is_verified": True, "reply_time": "<10 min"},
    {"business_name": "Events by Design GC", "city": "Gold Coast", "state": "QLD", "rating": 4.9, "review_count": 203, "is_verified": True, "reply_time": "<5 min"},
    {"business_name": "Gold Coast Wedding Hire", "city": "Gold Coast", "state": "QLD", "rating": 4.6, "review_count": 56, "is_verified": True, "reply_time": "<1 hour"},
    {"business_name": "Gold Coast Generator Hire", "city": "Gold Coast", "state": "QLD", "rating": 4.5, "review_count": 34, "is_verified": True, "reply_time": "<1 hour"},
    {"business_name": "Gold Coast Food Trucks", "city": "Gold Coast", "state": "QLD", "rating": 4.8, "review_count": 71, "is_verified": True, "reply_time": "<30 min"},
    {"business_name": "GC Inflatables", "city": "Gold Coast", "state": "QLD", "rating": 4.9, "review_count": 312, "is_verified": True, "reply_time": "<5 min"},
    {"business_name": "GC Photo Booths", "city": "Gold Coast", "state": "QLD", "rating": 4.7, "review_count": 98, "is_verified": True, "reply_time": "<10 min"},
]


def seed():
    client = get_client()

    print("Seeding categories...")
    for cat in CATEGORIES:
        try:
            client.table("categories").upsert(cat, on_conflict="slug").execute()
        except Exception as e:
            print(f"  Skipping category {cat['name']}: {e}")

    print("Seeding stores...")
    for store in STORES:
        try:
            client.table("stores").upsert(store, on_conflict="business_name").execute()
        except Exception as e:
            print(f"  Skipping store {store['business_name']}: {e}")

    print("Seeding products...")
    count = 0
    for prod in PRODUCTS:
        try:
            client.table("products").upsert(prod, on_conflict="rentsy_slug").execute()
            count += 1
            print(f"  ✅ {prod['name']}")
        except Exception as e:
            print(f"  ❌ {prod['name']}: {e}")

    print(f"\nDone! {count} products, {len(STORES)} stores, {len(CATEGORIES)} categories loaded.")


if __name__ == "__main__":
    seed()
